### ISSUE TITLE
Not running on El Capitan

### ISSUE THREAD

**Issue by stickperson** [munkie/acestream-docker#3]
I try running the image with: `$ docker run -v $HOME/Documents:/home/ace/Documents:rw -v /dev/snd:/dev/snd --privileged -v /tmp/.X11-unix:/tmp/.X11-unix -e uid=$(id -u) -e gid=$(id -g) -e DISPLAY=unix$DISPLAY --rm munkie/acestreamplayer` and get the following error:

```
docker: Error response from daemon: Mounts denied:
The path /dev/snd
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

I investigated a bit and the `/dev/snd` doesn't exist. Do you have to do something different on OSX?

**Comment by munkie** [comment]
@stickperson This continer is intended ti be run on linux, not OSX
